### ISSUE TITLE
SNS with SES

### ISSUE THREAD

**Issue by nasirkhan** [rennokki/laravel-sns-events#8]
Did you used SNS for SES notifications, like bounced and delivered mails? I installed this package and do verified the SNS notification subscription but not receiving the notification on the application endpoint.

**Comment by rennokki** [comment]
To make it work:
- create a SNS topic like this package tells you to
- create a SES Configuration Set (with the desired statuses) that will deliver the message to the SNS topic you just created
- when sending the mail (either by Laravel or by a new SesClient instance), specify the name of the configuration set you just created in the `ConfigurationSets` setting

**Comment by nasirkhan** [comment]
Thank you very much for your prompt reply. 
I created the configuration set and need to test if it works perfectly. 

I am using Laravel for sending emails, can you please tell me how can i add this ConfigurationSets? i could not find any detailed doc on this topic.

**Comment by rennokki** [comment]
You can find in the docs: https://laravel.com/docs/5.8/mail#driver-prerequisites

Search under SES Driver. You will find that the `ConfigurationSetName` variable should be set in `services`.

**Comment by nasirkhan** [comment]
You are awesome. 
I just find this setting in the doc, but thank you for the help.
